language: node_js

node_js:
  - "7"

install:
  - export PATH=$PATH:$HOME/google-cloud-sdk/bin
  - mkdir -p $HOME/.gcloud
  - echo $GCLOUD_KEY_FILE > $HOME/.gcloud/creds && chmod 600 $HOME/.gcloud/creds
  - curl https://sdk.cloud.google.com | bash
  - gcloud auth activate-service-account --key-file=$HOME/.gcloud/creds

script:
  - make test
  - make build
  - make deploy

notifications:
  email: false
