language: node_js

node_js:
  - "10"

addons:
  apt:
    sources:
    - sourceline: 'deb http://packages.cloud.google.com/apt cloud-sdk-trusty main'
      key_url: 'https://packages.cloud.google.com/apt/doc/apt-key.gpg'
    packages:
    - google-cloud-sdk

install:
  - make ci_setup

script:
  - make install test build deploy

notifications:
  email: false
