export const ResumeText = {
  preface:
    "I'm a motivated and self directed individual with a passion for learning anything new.  My skillset helps me to provide a fully cloud native software lifecycle, from design and development, to testing and deployment.  Strong communication skills and being very familiar with Agile software practices, I am capable of interacting and fitting into almost any team.",
  info: {
    location: 'Portland (Metropolitan Area), OR',
    email: 'daniel@danielhess.me',
    status: 'Open to offers',
    remote: 'Prefer in office/person over remote work',
  },
  accomplishments: ['Eagle Scout'],
  education: [
    {
      school: 'Christian Brothers University',
      location: 'Memphis, TN',
      start: 'August 2005',
      end: 'May 2009',
      degrees: [
        'B.S. in Computer Engineering',
        'B.S. in Computer Science',
        'Minor in Mathematics',
      ],
    },
  ],
  positions: [
    {
      title: 'Senior Software Engineer',
      company: 'Ion Channel',
      location: 'Portland, OR',
      start: 'September 2016',
      end: 'Present',
      achievements: [
        'Served as Golang expert for team and ensured best practices for proficiency',
        'Created open source Golang & Node SDKs for interaction with API',
        'Forced public SDK accuracy by using SDK in the API’s services',
        'Filled duties as Project manager when previous one left',
        'Helped establish pattern to strangle older Ruby services',
        'Migrated several services from Ruby to Golang',
        'Formalized and cleaned up the build process for all services',
        'Created skeleton for new Golang services to provide consistency in service startup and running',
        'Wrote several new services for integrations with external sources like Github and S3',
        'Provided proof of concept and added role based access to API',
        'Migrated several services from remote testing to local testing',
        'Assisted in the redesign of logging infrastructure',
        'Wrote statting library for Go services',
        'Took on UI leadership when previous UI dev left',
        'Architected several new features spanning across UI and API and implemented UI side',
        'Implemented several redesigns of pages within the UI',
        'Significantly reduced complexity and size of UI code base',
      ],
    },
    {
      title: 'Senior Software Engineer',
      company: 'Treetop Commons, LLC',
      location: 'Portland, OR',
      start: 'January 2016',
      end: 'September 2016',
      achievements: [
        'Wrote and collaborated on RESTful API for consumption by multiple clients',
        'Expanded and improved use of large graph data store built on Postgres',
        'Lead changes around best practices of Golang and automation for deployment',
        'Served as secondary for devops tasks to distribute knowledge and improve processes',
        'Created reproducible reports requested by customers',
        'Implemented acceptance tests for the API using Cucumber',
        'Added acceptance tests to build chain as a blocker to Pull Requests',
        'Created a dockerized environment of frontend projects to allow QA to test branches prior to merges',
        'Implemented vendoring of API dependencies to bulkhead against upstream changes and outages',
        'Drove changes in process to include sprint planning, estimation, grooming, and retrospectives',
      ],
    },
    {
      title: 'Devops Engineer',
      company: 'Monsoon Commerce',
      location: 'Portland, OR',
      start: 'June 2014',
      end: 'Dec 2015',
      achievements: [
        'Rewrote primary collection service from Java to Golang, reducing service cost by over half',
        'Significantly reduced AWS bill through coding and architectural changes on multiple occasions',
        'Implemented 12 factoring of all new projects and brought out of date old projects up to speed',
        'Created interfaces and architecture for web store integration project, significantly improving development time and maintainability',
        'Designed Makefiles to build and deploy code locally in the same manner as the build system',
        'Worked with QA to write Cucumber based acceptance tests for services',
        'Implemented regular backups of services’ data',
        'Integrated centralized key store for service configuration with service acceptance tests',
        'Dockerized several services for local testing and easier deployment',
        'Moved stating and monitoring infrastructure to dockerized services',
        'Pushed for culture of testing infrastructure and service resiliency to improve system uptime',
      ],
    },
    {
      title: 'System Administrator I',
      company: "St. Jude Children's Research Hospital",
      location: 'Memphis, TN',
      start: 'June 2013',
      end: 'June 2014',
      achievements: [
        'Wrote scripts to deploy software, gather information, and automate changes on all campus computers',
        'Assisted in Patch Management proof of concept and deployment into production',
        'Automated provisioning of Windows and Mac systems',
        'Served as team expert for Mac and Linux systems automation',
        'Implemented cloud enabled communication with Config Management Servers',
        'Created catalogue of automated tasks for users to self service their computers',
        'Performed migration of all domain attached machines from old to new structure',
        'Implemented Gitlab and use of Git for team internal projects',
        'Implemented Config Management policies to maintain minimum versions of Antivirus and Encryption',
        'Expanded automation workflow to wipe retired systems for automated lifecycle management',
        'Implemented remote asset tracking and security',
      ],
    },
    {
      title: 'Senior Technical Service Provider',
      company: "St. Jude Children's Research Hospital",
      location: 'Memphis, TN',
      start: 'January 2012',
      end: 'June 2013',
      achievements: [
        'Implemented application and database mirroring for disaster recovery of Inventory and Ticketing System',
        'Deployed Symantec Altiris 7.1 for Configuration Management',
        'Implemented software policies to enforce Config Management across all campus computers',
        'Automated regular tasks to run on multiple computers as part of Config Management',
        'Integrated data from inventory database into Altiris database',
        'Assisted in Active Directory OU structure redesign',
        'Designed custom web application to automate system disposals on mobile devices',
        'Implemented Mac integration with Configuration Management',
        'Redesigned and automated numerous workflows within Inventory Management system',
      ],
    },
    {
      title: 'Technical Service Provider',
      company: "St. Jude Children's Research Hospital",
      location: 'Memphis, TN',
      start: 'June 2009',
      end: 'January 2012',
      achievements: [
        'Performed complete rebuild and restructure of inventory and helpdesk ticket system',
        'Designed feature additions to inventory system',
        'Wrote SQL scripts to locate and resolve anomalies in inventory database',
        'Utilized data collected from multiple sources to analyze and update inventory for missing assets',
        'Integrated inventory details from external sources into inventory application',
        'Designed custom mobile interface for Client Services to access tickets on mobile devices',
        'Automated new ticketing and inventory workflows for helpdesk and field techs',
        'Designed and implemented structure to accommodate inventory and change control of data centers within existing inventory',
        'Unified disposition process for multiple departments assets to ensure HIPAA compliance',
        'Automated inventory reports for compliance and yearly budgeting',
        'Provided education and training on use of inventory and ticketing application to all of Client Services',
        'Assisted in creating a unified image for all desktop deployments',
      ],
    },
    {
      title: 'Student Intern PC Support Specialist',
      company: "St. Jude Children's Research Hospital",
      location: 'Memphis, TN',
      start: 'November 2005',
      end: 'June 2009',
      achievements: [
        'Converted handwritten, index card inventory to an Access database',
        'Automated report creation for disposition of inventory',
        'Designed and implemented paperless process for disposition of inventory',
        'Created custom web application to record and automate campus wide inventory',
        'Automated portions of new computer provisioning',
      ],
    },
  ],
  skills: [
    {
      category: 'languages',
      entries: [
        { name: 'Golang', level: 3 },
        { name: 'JavaScript', level: 2 },
        { name: 'Ruby', level: 2 },
        { name: 'Java', level: 1 },
        { name: 'PHP', level: 1 },
        { name: 'Python', level: 1 },
        { name: 'Make', level: 2 },
        { name: 'SQL', level: 3 },
        { name: 'Shell Scripts', level: 3 },
        { name: 'VimL', level: 1 },
      ],
    },
    {
      category: 'frameworks',
      entries: [
        { name: 'React', level: 2 },
        { name: 'Styled Components', level: 2 },
        { name: 'Cucumber', level: 3 },
        { name: 'Gorilla Mux', level: 3 },
        { name: 'Goblin/Gomega', level: 3 },
        { name: 'Sinatra', level: 2 },
      ],
    },
    {
      category: 'systems',
      entries: [
        { name: 'CentOS', level: 3 },
        { name: 'Red Hat Enterprise Linux', level: 3 },
        { name: 'Ubuntu', level: 3 },
        { name: 'Debian', level: 3 },
        { name: 'Mac OS X', level: 3 },
        { name: 'Windows', level: 2 },
      ],
    },
    {
      category: 'infrastructure',
      entries: [
        { name: 'Amazon Web Services', level: 3 },
        { name: 'Digitial Ocean', level: 2 },
        { name: 'Google Cloud Platform', level: 3 },
        { name: 'Kubernetes', level: 2 },
        { name: 'Postgres', level: 3 },
        { name: 'RabbitMQ', level: 3 },
        { name: 'Redis', level: 2 },
        { name: 'etcd', level: 3 },
        { name: 'Logstash', level: 2 },
        { name: 'Filebeat', level: 2 },
      ],
    },
    {
      category: 'tools',
      entries: [
        { name: 'Ansible', level: 2 },
        { name: 'Chef', level: 1 },
        { name: 'CircleCI', level: 3 },
        { name: 'Docker', level: 3 },
        { name: 'Git', level: 3 },
        { name: 'Graphite/Graphana', level: 3 },
        { name: 'Jenkins', level: 2 },
        { name: 'Packer', level: 3 },
        { name: 'RVM', level: 3 },
        { name: 'TravisCI', level: 3 },
        { name: 'Vagrant', level: 3 },
        { name: 'Vim/Vi', level: 3 },
      ],
    },
  ],
  references: [],
}
