name: Build
on: [push]

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-dept: 1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install
      run: make install

    - name: Linters
      run: make linters

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-dept: 1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install
      run: make install

    - name: Build
      run: make build

  deploy:
    name: Deploy
    needs: [linting, build]
#    if: endsWith(github.ref, '/master') == true
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-dept: 1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Deploy
      run: make install build deploy
