name: Build
on: [push]

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-dept: 1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install
      run: make install

    - name: Linters
      run: make linters

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-dept: 1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install
      run: make install

    - name: Build
      run: make build

    - run: make test

